all:
  hosts:
  children:
    rancher_servers:
      hosts:
        tf-rancher-server-0:
          ansible_host: 10.0.0.27
    rancher_masters:
      hosts:
        tf-rancher-master-0:
          ansible_host: 10.0.0.24
        tf-rancher-master-1:
          ansible_host: 10.0.0.34
    rancher_workers:
      hosts:
        tf-rancher-worker-0:
          ansible_host: 10.0.0.22
        tf-rancher-worker-1:
          ansible_host: 10.0.0.31
    all_cluster_nodes:
      children:
        rancher_masters:
        rancher_workers: