- name: Doing Stuff
  hosts: masters
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_alpine
  become: yes
  tasks:
    - name: Add Groups
      ansible.builtin.group:
        name: storage
        gid: 1200
    - name: Add users
      ansible.builtin.user:
        name: pig
        uid: 1000
        group: storage
          #        groups: docker,wheel
    - name: Add management ssh key
      ansible.posix.authorized_key:
        user: pig
        key: "{{ lookup('file','/home/pig/.ssh/id_rsa_alpine.pub') }}"
    - name: Update apk repository
      community.general.apk:
        update_cache: yes
    - name: Upgrade packages
      community.general.apk:
        upgrade: yes
        available: yes
    - name: Install needed packages
      community.general.apk:
        name: git,docker,sudo,qemu-guest-agent,udev,py-pip,docker-py
    - name: Add services to startup
      service:
        name: docker
        enabled: yes
        runlevel: default
        state: started
 