rancher_servers:
  hosts:
    tf-rancher-server-0:
      ansible_host: 10.0.0.27
  vars:
    rancher_server: https://10.0.0.34
    rancher_token: pmjjxxwljmpv6fvrgztjqkfj2stt7n62cfxtwp6xs8wx52ssbzjbqf
    rancher_checksum: 63adfa04b387e3df4dc9a15c4dec27a0c13f7169d50d07e5d55431d8754f6ada  
    rancher_version: latest
rancher_masters:
  hosts:
    tf-rancher-master-0:
      ansible_host: 10.0.0.24
    tf-rancher-master-1:
      ansible_host: 10.0.0.34    
  vars:
    rancher_server: https://10.0.0.27
    rancher_token: pmjjxxwljmpv6fvrgztjqkfj2stt7n62cfxtwp6xs8wx52ssbzjbqf
    rancher_checksum: 63adfa04b387e3df4dc9a15c4dec27a0c13f7169d50d07e5d55431d8754f6ada  
    rancher_version: v2.3.5
rancher_workers:
  hosts:
    tf-rancher-worker-0:
      ansible_host: 10.0.0.22
    tf-rancher-worker-1:
      ansible_host: 10.0.0.31
  vars:
    rancher_server: https://10.0.0.27
    rancher_token: pmjjxxwljmpv6fvrgztjqkfj2stt7n62cfxtwp6xs8wx52ssbzjbqf
    rancher_checksum: 63adfa04b387e3df4dc9a15c4dec27a0c13f7169d50d07e5d55431d8754f6ada  
    rancher_version: v2.3.5
