---
# tasks file for hostprep
- name: Change Hostname
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'
      # name: ansible-rancher-02
    use: alpine
- name: Change hosts file
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: 'template'
    replace: '{{ inventory_hostname }}'
- name: Add apk repository
  lineinfile:
    path: /etc/apk/repositories
    line: 'http://dl-cdn.alpinelinux.org/alpine/v3.14/community'
- name: Upgrade packages
  community.general.apk:
    upgrade: yes
    available: yes
    update_cache: yes
- name: Add services to startup
  service:
    name: local
    enabled: yes
    runlevel: default
    state: started